# clear the document and (re)create the user parameters.  globals: SIDE = 'left' | 'right'
exec(open('/Users/daiki/Projects/sage60/mechanical/case/fusion/fx.py').read())

PARAMS = [
    ('tilt', '5 deg', 'deg', '傾斜角（底面だけをこの角度で切る）'),
    ('plate_t', '1.2 mm', 'mm', 'プレート厚（MX もロープロと同じ 1.2mm の共通プレートを使う。2026-10-04）'),
    ('gasket_t', '1.5 mm', 'mm', 'ガスケット厚（タブの上下とも）'),
    ('clr', '0.3 mm', 'mm', '上下ケースの嵌め合いクリアランス'),
    ('tab_depth', '2.5 mm', 'mm', 'プレートのタブの長さ（形は駆動しない）'),
    ('wall', '2 mm', 'mm', '上ケース外壁の厚さ'),
    ('inner_r', '1.5 mm', 'mm', '内角R（CNCの工具半径以上）'),
    ('cav_z', '11 mm', 'mm', '空洞の深さ（プレート上面から）'),
    ('floor_t', '2 mm', 'mm', '床の厚さ（傾斜に沿う）'),
    ('mag_d', '6.1 mm', 'mm', '磁石穴径（ダイソーのφ6磁石、2026-10-03。前はφ2×2）'),
    ('mag_t', '3 mm', 'mm', '磁石の厚さ（ダイソー φ6×3、2026-10-03 確認）'),
    ('mag_h_top', 'mag_t + 0.1 mm', 'mm', '磁石穴の深さ（上ケース）'),
    ('mag_h', '2 * mag_t - mag_h_top + 0.2 mm', 'mm', '磁石穴の深さ（下ケース）。上の磁石が mag_h_top より厚い分だけ下に突き出るので、その分深くする'),
    ('outer_r', '2 mm', 'mm', '外形の角R（Pythonで計算・形は駆動しない）'),
    ('shelf_w', '3.7 mm', 'mm', '棚幅（形は駆動しない）'),
    ('pcb_gap', '3.8 mm', 'mm', 'プレート下面〜PCB上面（MX: プレート上面〜PCB上面 5.0）'),
    ('xiao_t', '1.4 mm', 'mm', 'PCB上面〜XIAO上面（基板1.2＋はんだで浮く0.17。SeeedのSTEPで確認）'),
    ('usb_h_c', '3.26 mm', 'mm', 'USB-Cレセプタクルの高さ'),
    ('usb_w', '15 mm', 'mm', 'USB開口の幅（形は駆動しない）'),
    ('usb_h', '9 mm', 'mm', 'USBの凹み（成形部用、角R2）の高さ（形は駆動しない）'),
    ('usb_rcpt_w', '9.8 mm', 'mm', '差込口の面の壁のレセプタクル穴の幅（角R1.6、形は駆動しない）'),
    ('usb_rcpt_h', '4.0 mm', 'mm', 'レセプタクル穴の高さ（形は駆動しない）'),
    ('ins_d', '1.6 mm', 'mm', 'MCUカバーのネジ下穴（M2タップ/セルフタップ）'),
    ('ins_h', '4 mm', 'mm', 'MCUカバーのネジ穴の深さ'),
    ('mcu_cover_z', '3.9 mm', 'mm', 'MCU部の壁の上面＝MCUカバーの下面（プレート上面基準）。USBの凹みの上に1.4mmの肉を残す（xiao_t 1.4 で 3.5→3.9）'),
    ('top_h', '7 mm', 'mm', '上ケース天面の高さ（プレート上面から）'),
    ('guard_z', '1 mm', 'mm', '親指〜MCU間のガード（上ケース）の下面。プレート上面から浮かせる（ガスケットで動くため）'),
    ('open_clr', '1 mm', 'mm', '上ケース開口とプレート本体の隙間（形は駆動しない）'),
    ('gasket_pocket', '1 mm', 'mm', 'ガスケット溝の深さ'),
    ('shelf_d', 'plate_t', 'mm', '上下の合わせ面（棚の上面）の深さ'),
    ('foot_d', '10.5 mm', 'mm', 'ゴム足の凹みの径（φ10ゴム足）'),
    ('foot_t', '1 mm', 'mm', 'ゴム足の凹みの深さ'),
]
TB_PARAMS = [
    ('tb_clr', '0.5 mm', 'mm', 'トラックボールケースとの隙間（形は駆動しない）'),
    ('tb_gap', '0.3 mm', 'mm', 'センサー箱の下面とPCB上面の隙間'),
    ('tb_leg_h', '3.7 mm', 'mm', 'トラックボールケース底面〜センサー箱下面（STL実測）'),
    ('tb_scr_d', '2.0 mm', 'mm', 'M1.7ネジの通し穴'),
    ('tb_cb_d', '3.6 mm', 'mm', 'M1.7ネジ頭の座ぐり径（机側）'),
    ('tb_cb_t', '2.0 mm', 'mm', '座ぐりの残し厚（座面の下）'),
    ('tb_deck_d', '2.5 mm', 'mm', 'トラックボール手前の床の深さ（棚の上面から）'),
]

# low profile (Choc on the same PCB): thinnest stack, no spare gaps
LP_PARAMS = {
    'tilt': ('0 deg', '傾斜角（LPは傾斜なし。底面は水平）'),
    'plate_t': ('1.2 mm', 'プレート厚（Choc）'),
    'pcb_gap': ('1 mm', 'プレート下面〜PCB上面（Choc: プレート上面〜PCB上面 2.2）'),
    'gasket_t': ('1 mm', 'ガスケット厚（タブの上下とも、潰す前）'),
    'gasket_pocket': ('-0.2 mm', 'ガスケット溝の余裕（負＝潰し量。1mm厚を0.8mmに潰す）'),
    'clr': ('0.2 mm', None),
    'wall': ('1.5 mm', None),
    'open_clr': ('0.5 mm', None),
    'cav_z': ('plate_t + pcb_gap + pcb_t + sock_h + bat_t + bat_clr', '空洞の深さ（プレート上面から）＝ソケットの下にバッテリー（JSTの4.85より深い）'),
    'floor_t': ('1.5 mm', None),
    'top_h': ('gasket_t + gasket_pocket + 1.2 mm', '上ケース天面の高さ（プレート上面から）＝ガスケット溝の上に1.2mm'),
    'mcu_cover_z': ('top_h - plate_t', 'MCU部の壁の上面。プレートと同じ厚さのMCUカバーが上ケース天面と面一になる高さ（USBの凹みとレセプタクルの穴は上が開いた切り欠きになる）'),
    'usb_h': ('8 mm', None),
    'guard_z': ('0.5 mm', None),
    'mag_h_top': ('2.1 mm', '磁石穴の深さ（上ケース）。リングが3.2mmしかないので上に1.1mm残し、磁石は下に0.9mm突き出す（下ケースの穴 mag_h が4.1になり、位置決めピンを兼ねる）'),
    'foot_t': ('0.5 mm', None),
}
LP_EXTRA = [
    ('pcb_t', '1.6 mm', 'mm', 'PCB厚'),
    ('sock_h', '1.8 mm', 'mm', 'ホットスワップソケットの高さ（PCB下面から）'),
    ('bat_t', '5.5 mm', 'mm', 'バッテリー厚（EEMB 552036 360mAh: 5.5×20×36）'),
    ('bat_clr', '0.5 mm', 'mm', 'バッテリーの膨らみ代'),
]

def ensure_doc():
    if any(d.name.startswith(DOC) for d in app.documents): return
    doc = app.documents.add(adsk.core.DocumentTypes.FusionDesignDocumentType)
    prj = [p for p in app.data.dataProjects if p.name == 'Admin Project'][0]
    doc.saveAs(DOC, prj.rootFolder, 'sage60 low-profile case (generated by mechanical/case/fusion)', '')

def run(_c):
    ensure_doc()
    d = design(DOC)
    d.designType = adsk.fusion.DesignTypes.ParametricDesignType
    tl = d.timeline
    tl.markerPosition = 0
    tl.deleteAllAfterMarker()
    up = d.userParameters
    for _ in range(10):         # dependents first (deleteMe fails while another parameter refers to it)
        for p in [up.item(i) for i in range(up.count)][::-1]:
            if not p.dependentParameters.count: p.deleteMe()
    assert up.count == 0
    ps = []
    for n, e, u, cm in (LP_EXTRA if LP else []) + PARAMS + (TB_PARAMS if SIDE == 'right' else []):
        if LP and n in LP_PARAMS:
            e, c2 = LP_PARAMS[n]; cm = c2 or cm
        ps.append((up.add(n, VI.createByString('1 ' + u), u, cm), e))
    for p, e in ps:             # expressions may refer to parameters added later
        p.expression = e
    print(SIDE, 'timeline', tl.count, 'params', up.count, 'bodies', d.rootComponent.bRepBodies.count)
