name: Create Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          github-api-url: "https://github.acme-inc.com/api/v3"
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: simple